"""Task function registry for KARMA.

Manages dynamically generated and pre-defined task functions,
providing execution and registration capabilities.
"""

import importlib
import importlib.util
import logging
import sys
from pathlib import Path
from typing import Any, Callable, Dict, Optional, Union

logger = logging.getLogger("karma.planning.registry")


class TaskFunctionRegistry:
    """Registry for managing task functions generated by the LLM.

    Supports dynamic loading of functions from task_functions.py
    and execution by name.
    """

    def __init__(self, module_name: str = "task_functions", file_path: Optional[Union[str, Path]] = None):
        self.module_name = module_name
        self._module = None
        self._file_path = Path(file_path) if file_path else None

    def reload(self, file_path: Optional[Union[str, Path]] = None) -> None:
        """Reload the task_functions module.

        Args:
            file_path: Optional path to the task_functions.py file.
        """
        path = Path(file_path) if file_path else self._file_path
        try:
            if path and path.exists():
                spec = importlib.util.spec_from_file_location(self.module_name, path)
                if spec and spec.loader:
                    self._module = importlib.util.module_from_spec(spec)
                    sys.modules[self.module_name] = self._module
                    spec.loader.exec_module(self._module)
                    logger.info("Reloaded task_functions module from %s", path)
                    return
            self._module = importlib.import_module(self.module_name)
            importlib.reload(self._module)
            logger.info("Reloaded task_functions module")
        except ImportError as e:
            logger.error("Failed to import task_functions: %s", e)
            self._module = None

    def get_function(self, name: str) -> Optional[Callable]:
        """Get a function by name from the task_functions module."""
        if self._module is None:
            self.reload()
        if self._module is None:
            return None
        return getattr(self._module, name, None)

    def execute(self, function_name: str, robot, **kwargs) -> bool:
        """Execute a named task function with a robot argument.

        Args:
            function_name: Name of the function to execute.
            robot: Robot instance to pass as first argument.
            **kwargs: Additional arguments for the function.

        Returns:
            True if the function was found and executed.
        """
        func = self.get_function(function_name)
        if func is None:
            logger.error("Task function not found: %s", function_name)
            return False
        try:
            func(robot, **kwargs)
            return True
        except Exception as e:
            logger.error("Task function execution failed: %s", e)
            return False

    def list_functions(self) -> Dict[str, Callable]:
        """List all callable functions in the task_functions module."""
        if self._module is None:
            self.reload()
        if self._module is None:
            return {}
        return {
            name: obj
            for name, obj in vars(self._module).items()
            if callable(obj) and not name.startswith("_")
        }
