"""Auto-generated task functions.

This file is auto-generated by KARMA's task decomposition system.
Do not edit this file manually.
"""
from scripts.action_wrappers import *

def wash_apple(robot):
    # ── SubTask 1: Find and pick up the Apple ──
    available_positions = [
        (-1.0, 0.0, 0.0),     # CounterTop with multiple drawers
        (-0.25, 0.0, -1.5),   # CounterTop near Microwave and Stove
        (-1.0, 0.0, -1.5),    # CounterTop near Sink
        (-2.0, 0.0, 2.0),     # Fridge and GarbageCan area
        (0.5, 0.0, 1.5),
        (1.25, 0.0, -1.75),   # Shelving Unit location
        (1.5, 0.0, -0.25),    # LightSwitch location
        (1.5, 0.0, 1.0),
    ]
    # Step 1: Explore to find the Apple
    Explore(robot, 'Apple', available_positions)
    # Step 2: Navigate directly to the Apple once found
    GoToObject(robot, 'Apple')
    # Step 3: Pick up the Apple
    PickupObject(robot, 'Apple')

    # ── SubTask 2: Wash the Apple in the Sink ──
    # Step 4: Navigate to the Sink
    GoToObject(robot, 'Sink')
    # Step 5: Place the Apple into the Sink basin (required before cleaning)
    PutObject(robot, 'Apple', 'Sink')
    # Step 6: Turn on the faucet (water must be running to wash)
    SwitchOn(robot, 'Faucet')
    # Step 7: Clean/Wash the Apple under running water
    CleanObject(robot, 'Apple')
