"""Auto-generated task functions.

This file is auto-generated by KARMA's task decomposition system.
Do not edit this file manually.
"""
from scripts.action_wrappers import *

def wash_apple(robot):
    # 0: SubTask 1: Wash the apple
    # 1: Explore the Apple.
    available_positions = [
        (-1.0, 0, 0),  # CounterTop, likely location for Apple
        (-0.25, 0, -1.5),  # CounterTop, Microwave area
        (-1.0, 0, -1.5),  # Sink area
        (-2.0, 0, 2.0),  # Fridge area
        (1.25, 0, -1.75),  # ShelvingUnit area
        (1.5, 0, -0.25),  # LightSwitch area
        (1.5, 0, 1.0),  # Empty area
        (0.5, 0, 1.5)  # Empty area
    ]
    Explore(robot, 'Apple', available_positions)
    # 2: Pick up the Apple.
    PickupObject(robot, 'Apple')
    # 3: Go to the Sink.
    GoToObject(robot, 'Sink')
    # 4: Wash the Apple in the Sink.
    CleanObject(robot, 'Apple')
